name: Reusable workflow example

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - run: Install-Module -Name PSToml -Scope AllUsers
      shell: pwsh
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: "release"
    - name: Install Julia versions
      run: |
        $channels = "1.6", "1.10"
        $channels | % {juliaup add $_}        
      shell: pwsh
    - name: Run tests
      run: |
        $channels = "1.6", "1.10"


        $channels | % {
          $Env:JULIA_DEPOT_PATH = "~/.julia-$_"
          
          julia +$_ --project=. -e 'using Pkg; Pkg.Registry.add("General")'
          julia +$_ --project=. -e 'using Pkg; Pkg.instantiate()'
        }

        julia +$_ --project=. -e 'println("We are in ", pwd())'

        $channels | % -parallel {
          $Env:JULIA_DEPOT_PATH = "~/.julia-$_"
          julia +$_ --project=. -e 'println("We are in ", pwd())'
          
          julia +$_ --project=. -e 'using Pkg; Pkg.test()'
        }
      shell: pwsh
