name: Reusable workflow example

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/julia-lint@main
  test:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: "release"
    - name: Compute channels from Project.toml bounds
      id: compute_juliaup_channels
      run: julia ./versionlogic/versionlogic.jl
    - name: Install Julia versions
      run: |
        $channels = ${{ steps.compute_juliaup_channels.outputs.juliaup_channels }}
        $channels | % {juliaup add $_}        
      shell: pwsh
    - name: Clone registries
      run: |
        $channels = "1.6", "1.10"

        $channels | % {
          $Env:JULIA_DEPOT_PATH = "${{ runner.tool_cache }}/juliadepots/julia-$_"
          
          julia +$_ --project=. -e 'using Pkg; Pkg.Registry.add("General")'
        }
      shell: pwsh
    - name: Instantiate and precompile
      run: |
        $channels = "1.6", "1.10"

        $channels | % {
          $Env:JULIA_DEPOT_PATH = "${{ runner.tool_cache }}/juliadepots/julia-$_"
          
          julia +$_ --project=. --startup-file=no --history-file=no --depwarn=no -e 'using Pkg; Pkg.instantiate()'
        }
      shell: pwsh
    - name: Install test runner
      run: julia --project=./testrunner -e 'using Pkg; Pkg.instantiate()'
    - name: Run tests
      run: |
        $channels = "1.6", "1.10"

        julia --project=./testrunner ./testrunner/main.jl ${{ runner.tool_cache }} @channels
      shell: pwsh
    - name: Run CTRF annotations
      run: npx github-actions-ctrf testresults.json
      if: always()
