name: Julia CI

on:
  push: {branches: [main,master]}
  pull_request: {types: [opened,synchronize,reopened]}
  issue_comment: {types: [created]}
  schedule: [{cron: 0 0 * * *}]
  workflow_dispatch:

jobs:
  julia-ci:
    uses: julia-vscode/testitem-workflow/.github/workflows/testitemci.yml@v1
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
