name: Julia CI

on:
  push: {branches: [main,master]}
  pull_request: {types: [opened,synchronize,reopened]}
  issue_comment: {types: [created]}
  schedule: [{cron: '0 0 * * *'}]
  workflow_dispatch:
    inputs:
      feature:
        type: choice
        description: What to run
        options: 
        - CompatHelper
        - TagBot

permissions: write-all

jobs:
  julia-ci:
    uses: julia-vscode/testitem-workflow/.github/workflows/juliaci.yml@main
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
