name: NEW MAIN CI

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    uses: ./callable.yml
    with:
        os: ${{ matrix.os }}
