name: NEW MAIN CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  julia-ci:
    uses: ./.github/workflows/callable.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
